# -*- coding: utf-8 -*-
"""pyint1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11oFvueBu7og5cAXXn9XYrNhb_AD6_Gms
"""

#lab 1
#1

def calc():
  a = int(input("Enter length of the triangle:"))
  b = int(input("enter breath of the triangle:"))
  return a*b

calc()

#2

def calc():
  kg = int(input("Enter weight:"))
  m = int(input("enter height:"))
  return (kg/(m^2))*100

calc()

#3
Student = {}
continue_1 = 'TRUE'
while continue_1 == 'TRUE':
    Student_name = input('Enter name of student')
    marks = input('Enter their marks').split(',')
    if Student_name not in Student:
        Student[Student_name] = marks
    continue_1 = input('Do you still want to continue, TRUE OR FALSE')
    if continue_1 == 'FALSE':
        break

print(Student)

#lab2
#4

age= int(input("age:"))

if age<18:
  print("Minor ")
elif age>18:
  print("Major")
elif age>=65:
  print("Senior")
else:
  print("Wrong data")

#5
for i in range(1,50):
  if (i%2==0):
    print(i)
  else:
    pass

#6
def get_password(prompt="Enter the password: "):
    while True:
        password = input(prompt)
        if password == "ashish":
            print("Correct password entered.")
            break
        else:
            print("Incorrect password. Please try again.")

get_password()

#lab3
#7
num=[4,6,8,2]

def avgs(num):
  return sum(num)/len(num)

print(avgs(num))

#8
def count_vowels(s):
    vowels = "aeiouAEIOU"
    count = 0

    for char in s:
        if char in vowels:
            count += 1

    return count

string = "Favtutoru article"
print("Number of vowels in the given string is: ", count_vowels(string))

#9
from datetime import datetime
current_date= datetime.now()
print(current_date)

#lab4
#10
try:
    a = int(input('Enter first value'))
    b = int(input('Enter the second value'))
    print(a+b)
except ValueError:
    print('Non-numeric inputs not allowed')

#11
try:
    a = int(input('Enter an integer value'))
    print(a)
except ValueError:
    print('The value cannot be a non integer')

#12
def division_function(a,b):
    try:
        return b/a
    except ZeroDivisionError:
        print('Division by zero is not possible')

#lab 5
#13
f = open('Python.txt','w')
f.writelines('Hello,Python!')

#14
f = open('Python.txt','r')
f.readlines()

#15
f = open('Python.txt','a')
f.writelines('Good to see you here')

f = open('Python.txt','r')
f.readlines()

